import React, { createContext, useContext, useEffect, useMemo, useState } from "react";

export type Language = "en" | "zh";

const STORAGE_KEY = "atoms.language";

const translations = {
  en: {
    "nav.home": "Home",
    "nav.dashboard": "Dashboard",
    "nav.explore": "Explore",
    "nav.pricing": "Pricing",
    "nav.resources": "Resources",
    "nav.workspaceDemo": "Workspace Demo",
    "nav.architecture": "Architecture",
    "nav.settings": "Settings",
    "nav.profile": "Profile",
    "nav.logout": "Log out",
    "nav.login": "Log in",
    "nav.signup": "Sign up",
    "nav.credits": "credits",
    "language.switchToChinese": "Switch language to Chinese",
    "language.switchToEnglish": "切换语言到英文",
    "auth.welcomeBack": "Welcome back",
    "auth.loginSubtitle": "Sign in to your Vibe Coding Studio account",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.forgotPassword": "Forgot password?",
    "auth.signIn": "Sign in",
    "auth.signingIn": "Signing in…",
    "auth.orContinueWith": "Or continue with",
    "auth.checkingGoogle": "Checking Google sign-in…",
    "auth.redirecting": "Redirecting…",
    "auth.continueWithGoogle": "Continue with Google",
    "auth.googleUnavailable": "Google sign-in is not configured in this environment yet.",
    "auth.noAccount": "Don't have an account?",
    "auth.signUp": "Sign up",
    "auth.resendVerification": "Resend verification email",
    "auth.verificationSent": "Verification link sent! Check your inbox.",
    "auth.resendFailed": "Failed to resend. Please try again later.",
    "auth.signInFailed": "Sign in failed",
    "auth.googleFailed": "Google sign in failed",
    "auth.createAccountTitle": "Create an account",
    "auth.createAccount": "Create account",
    "auth.registerSubtitle": "Start building with AI for free",
    "auth.name": "Name",
    "auth.optional": "(optional)",
    "auth.confirmPassword": "Confirm password",
    "auth.passwordPlaceholder": "Min. 8 characters",
    "auth.confirmPasswordPlaceholder": "Repeat password",
    "auth.creatingAccount": "Creating account…",
    "auth.alreadyHaveAccount": "Already have an account?",
    "auth.checkInbox": "Check your inbox",
    "auth.verificationEmailSent": "We sent a verification link to",
    "auth.activateAccount": "Click it to activate your account.",
    "auth.backToSignIn": "Back to sign in →",
    "auth.passwordsMismatch": "Passwords do not match.",
    "auth.passwordTooShort": "Password must be at least 8 characters.",
    "auth.registrationFailed": "Registration failed",
    "landing.heroBadge": "Powered by AI Agent Technology",
    "landing.heroLine1": "Turn ideas into",
    "landing.heroLine2": "software",
    "landing.heroDescription": "Vibe Coding Studio is an AI-powered development platform where intelligent agents collaborate to build, test, and deploy your applications from idea to production in minutes.",
    "landing.startBuilding": "Start Building Free",
    "landing.creatingProject": "Creating Project...",
    "landing.exploreProjects": "Explore Projects",
    "landing.projectsBuilt": "Projects Built",
    "landing.activeUsers": "Active Users",
    "landing.uptime": "Uptime",
    "landing.coreFeatures": "Core Features",
    "landing.featuresTitlePrefix": "Everything you need to",
    "landing.featuresTitleHighlight": "build fast",
    "landing.featuresSubtitle": "From AI-powered code generation to one-click deployment, Vibe Coding Studio provides a complete development workflow.",
    "landing.featureAiTitle": "AI Agent Team",
    "landing.featureAiDescription": "A team of specialized AI agents — Engineer, Designer, PM, Data Analyst — collaborate to build your project from idea to deployment.",
    "landing.featureCodeTitle": "Smart Code Editor",
    "landing.featureCodeDescription": "Real-time code generation with syntax highlighting, file management, and intelligent suggestions powered by multiple LLM models.",
    "landing.featurePreviewTitle": "Live App Viewer",
    "landing.featurePreviewDescription": "Preview your application in real-time as it's being built. Replace elements, add images, and publish with one click.",
    "landing.featureDeployTitle": "One-Click Deploy",
    "landing.featureDeployDescription": "Deploy your projects instantly to production with custom domains, SSL, and global CDN. No DevOps knowledge required.",
    "landing.modernTeamsPrefix": "Built for",
    "landing.modernTeamsHighlight": "modern teams",
    "landing.modernTeamsSubtitle": "Whether you're a solo developer or a growing startup, Vibe Coding Studio scales with your needs.",
    "landing.pricingTitle": "Pricing",
    "landing.pricingSubtitle": "Free to start. Flexible to scale.",
    "landing.monthly": "Monthly",
    "landing.annual": "Annual",
    "landing.save21": "Save 21%",
    "landing.faqTitle": "Frequently Asked Questions",
    "landing.faqSubtitlePrefix": "See our",
    "landing.helpCenter": "Help center",
    "landing.faqSubtitleSuffix": "for more info",
    "landing.ctaPrefix": "Ready to build with",
    "landing.ctaHighlight": "AI?",
    "landing.ctaDescription": "Join thousands of developers and teams building the future with Vibe Coding Studio. Start for free, no credit card required.",
    "landing.getStarted": "Get Started Free",
    "landing.footerTagline": "Turn ideas into products that sell",
    "landing.footerProduct": "Product",
    "landing.footerResources": "Resources",
    "landing.footerAbout": "About",
    "landing.footerCommunity": "Community",
    "landing.footerRights": "© 2024 Vibe Coding Studio. All rights reserved.",
    "workspace.engineer": "Engineer",
    "workspace.team": "Team",
    "workspace.chat": "Chat",
    "workspace.editor": "Editor",
    "workspace.appViewer": "App Viewer",
    "workspace.terminal": "Terminal",
    "workspace.share": "Share",
    "workspace.publish": "Publish",
    "workspace.ready": "Ready",
    "workspace.demoMode": "Demo Mode",
    "dashboard.welcomeBack": "Welcome back",
    "dashboard.projectsCount": "projects",
    "dashboard.projectCount": "project",
    "dashboard.newProject": "New Project",
    "dashboard.searchProjects": "Search projects...",
    "dashboard.noProjectsFound": "No projects found",
    "dashboard.noProjectsYet": "No projects yet",
    "dashboard.tryDifferentSearch": "Try a different search term",
    "dashboard.createFirstProject": "Create your first project to get started",
    "dashboard.createProject": "Create Project",
    "dashboard.noDescription": "No description",
    "dashboard.createNewProject": "Create New Project",
    "dashboard.projectName": "Project Name",
    "dashboard.description": "Description",
    "dashboard.descriptionPlaceholder": "A brief description of your project",
    "dashboard.framework": "Framework",
    "dashboard.visibility": "Visibility",
    "dashboard.private": "Private",
    "dashboard.public": "Public",
    "dashboard.secret": "Secret",
    "dashboard.cancel": "Cancel",
    "dashboard.create": "Create",
  },
  zh: {
    "nav.home": "首页",
    "nav.dashboard": "控制台",
    "nav.explore": "探索",
    "nav.pricing": "价格",
    "nav.resources": "资源",
    "nav.workspaceDemo": "工作台演示",
    "nav.architecture": "架构",
    "nav.settings": "设置",
    "nav.profile": "个人资料",
    "nav.logout": "退出登录",
    "nav.login": "登录",
    "nav.signup": "注册",
    "nav.credits": "额度",
    "language.switchToChinese": "Switch language to Chinese",
    "language.switchToEnglish": "切换语言到英文",
    "auth.welcomeBack": "欢迎回来",
    "auth.loginSubtitle": "登录你的 Vibe Coding Studio 账号",
    "auth.email": "邮箱",
    "auth.password": "密码",
    "auth.forgotPassword": "忘记密码？",
    "auth.signIn": "登录",
    "auth.signingIn": "登录中…",
    "auth.orContinueWith": "或使用以下方式继续",
    "auth.checkingGoogle": "正在检查 Google 登录…",
    "auth.redirecting": "正在跳转…",
    "auth.continueWithGoogle": "使用 Google 继续",
    "auth.googleUnavailable": "当前环境尚未配置 Google 登录。",
    "auth.noAccount": "还没有账号？",
    "auth.signUp": "注册",
    "auth.resendVerification": "重新发送验证邮件",
    "auth.verificationSent": "验证链接已发送，请检查邮箱。",
    "auth.resendFailed": "重新发送失败，请稍后再试。",
    "auth.signInFailed": "登录失败",
    "auth.googleFailed": "Google 登录失败",
    "auth.createAccountTitle": "创建账号",
    "auth.createAccount": "创建账号",
    "auth.registerSubtitle": "免费开始使用 AI 构建应用",
    "auth.name": "姓名",
    "auth.optional": "（可选）",
    "auth.confirmPassword": "确认密码",
    "auth.passwordPlaceholder": "至少 8 个字符",
    "auth.confirmPasswordPlaceholder": "再次输入密码",
    "auth.creatingAccount": "正在创建账号…",
    "auth.alreadyHaveAccount": "已有账号？",
    "auth.checkInbox": "检查你的邮箱",
    "auth.verificationEmailSent": "我们已向这个邮箱发送验证链接：",
    "auth.activateAccount": "点击链接即可激活账号。",
    "auth.backToSignIn": "返回登录 →",
    "auth.passwordsMismatch": "两次输入的密码不一致。",
    "auth.passwordTooShort": "密码至少需要 8 个字符。",
    "auth.registrationFailed": "注册失败",
    "landing.heroBadge": "由 AI Agent 技术驱动",
    "landing.heroLine1": "把想法变成",
    "landing.heroLine2": "软件",
    "landing.heroDescription": "Vibe Coding Studio 是一个 AI 驱动的应用开发平台，智能 Agent 会协作完成构建、测试和预览，把想法快速变成可运行的产品。",
    "landing.startBuilding": "免费开始构建",
    "landing.creatingProject": "正在创建项目...",
    "landing.exploreProjects": "探索项目",
    "landing.projectsBuilt": "已构建项目",
    "landing.activeUsers": "活跃用户",
    "landing.uptime": "稳定运行",
    "landing.coreFeatures": "核心功能",
    "landing.featuresTitlePrefix": "快速构建所需的一切",
    "landing.featuresTitleHighlight": "都在这里",
    "landing.featuresSubtitle": "从 AI 代码生成到一键预览和部署，Vibe Coding Studio 提供完整的开发工作流。",
    "landing.featureAiTitle": "AI Agent 团队",
    "landing.featureAiDescription": "工程师、设计师、产品经理和数据分析 Agent 协作，把你的想法推进到可运行应用。",
    "landing.featureCodeTitle": "智能代码编辑器",
    "landing.featureCodeDescription": "实时生成代码，支持语法高亮、文件管理和由多模型驱动的智能建议。",
    "landing.featurePreviewTitle": "实时应用预览",
    "landing.featurePreviewDescription": "应用构建过程中即可实时预览，调整元素、添加图片并准备发布。",
    "landing.featureDeployTitle": "一键部署",
    "landing.featureDeployDescription": "将项目发布到生产环境，支持自定义域名、SSL 和全球 CDN，无需 DevOps 经验。",
    "landing.modernTeamsPrefix": "为",
    "landing.modernTeamsHighlight": "现代团队",
    "landing.modernTeamsSubtitle": "无论是个人开发者还是成长中的团队，Vibe Coding Studio 都能配合你的节奏扩展。",
    "landing.pricingTitle": "价格",
    "landing.pricingSubtitle": "免费开始，灵活扩展。",
    "landing.monthly": "月付",
    "landing.annual": "年付",
    "landing.save21": "省 21%",
    "landing.faqTitle": "常见问题",
    "landing.faqSubtitlePrefix": "更多信息请查看",
    "landing.helpCenter": "帮助中心",
    "landing.faqSubtitleSuffix": "",
    "landing.ctaPrefix": "准备好用",
    "landing.ctaHighlight": "AI 构建了吗？",
    "landing.ctaDescription": "和更多开发者与团队一起，用 Vibe Coding Studio 构建未来产品。免费开始，无需信用卡。",
    "landing.getStarted": "免费开始",
    "landing.footerTagline": "把想法变成能销售的产品",
    "landing.footerProduct": "产品",
    "landing.footerResources": "资源",
    "landing.footerAbout": "关于",
    "landing.footerCommunity": "社区",
    "landing.footerRights": "© 2024 Vibe Coding Studio. 保留所有权利。",
    "workspace.engineer": "工程师",
    "workspace.team": "团队",
    "workspace.chat": "对话",
    "workspace.editor": "编辑器",
    "workspace.appViewer": "应用预览",
    "workspace.terminal": "终端",
    "workspace.share": "分享",
    "workspace.publish": "发布",
    "workspace.ready": "就绪",
    "workspace.demoMode": "演示模式",
    "dashboard.welcomeBack": "欢迎回来",
    "dashboard.projectsCount": "个项目",
    "dashboard.projectCount": "个项目",
    "dashboard.newProject": "新建项目",
    "dashboard.searchProjects": "搜索项目...",
    "dashboard.noProjectsFound": "没有找到项目",
    "dashboard.noProjectsYet": "还没有项目",
    "dashboard.tryDifferentSearch": "换个关键词试试",
    "dashboard.createFirstProject": "创建第一个项目开始使用",
    "dashboard.createProject": "创建项目",
    "dashboard.noDescription": "暂无描述",
    "dashboard.createNewProject": "创建新项目",
    "dashboard.projectName": "项目名称",
    "dashboard.description": "描述",
    "dashboard.descriptionPlaceholder": "简单描述一下这个项目",
    "dashboard.framework": "框架",
    "dashboard.visibility": "可见性",
    "dashboard.private": "私密",
    "dashboard.public": "公开",
    "dashboard.secret": "链接可见",
    "dashboard.cancel": "取消",
    "dashboard.create": "创建",
  },
} as const;

type TranslationKey = keyof typeof translations.en;

interface LanguageContextValue {
  language: Language;
  setLanguage: (language: Language) => void;
  toggleLanguage: () => void;
  t: (key: TranslationKey) => string;
}

const defaultContext: LanguageContextValue = {
  language: "en",
  setLanguage: () => {},
  toggleLanguage: () => {},
  t: (key) => translations.en[key] ?? key,
};

const LanguageContext = createContext<LanguageContextValue>(defaultContext);

function getInitialLanguage(): Language {
  if (typeof window === "undefined") return "en";
  const stored = window.localStorage.getItem(STORAGE_KEY);
  if (stored === "zh" || stored === "en") return stored;
  return window.navigator.language.toLowerCase().startsWith("zh") ? "zh" : "en";
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(getInitialLanguage);

  const setLanguage = (nextLanguage: Language) => {
    setLanguageState(nextLanguage);
  };

  useEffect(() => {
    window.localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language === "zh" ? "zh-CN" : "en";
  }, [language]);

  const value = useMemo<LanguageContextValue>(
    () => ({
      language,
      setLanguage,
      toggleLanguage: () => setLanguage(language === "en" ? "zh" : "en"),
      t: (key) => translations[language][key] ?? translations.en[key] ?? key,
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
